packages:
  core: !include muino-water-meter-esp32.yaml

esphome:
  project:
    name: esphome.muino-water-meter
    version: dev # This will be replaced by the github workflows with the `release` version

dashboard_import:
  package_import_url: github://martijnvwezel/watermeter-esphome/muino-water-meter-esp32.yaml@main

# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.
# esp32_improv:
#   authorizer: none

# Sets up the improv via serial client for Wi-Fi provisioning.
# Handy if your device has a usb port for the user to add credentials when they first get it.
# improv_serial: