# Muino Water Meter ESP32 Configuration
# This configuration is designed for an ESP32-based water meter sensor using light sensors to detect flow.
# It includes calibration options, flow rate and consumption calculations, and a debug mode for troubleshooting.
#
# Written by:
#  - Martijn van Wezel (@martijnvwezel)
#  - Arjan Mels (@arjanmels)

# These substitutions allow the end user to override certain values
substitutions:
  # Interval between sensor readings
  sample_interval: 100ms
  # Number of samples to take for each reading
  samples_per_reading: 10
  # Number of initial readings to discard for stabilization
  initialization_readings: 20
  # Window size for the moving averaging over the readings
  window_size: 3

  # These bounds are used to filter out unrealistic readings, adjust as needed based on your sensor
  lower_bound: 0.001
  upper_bound: 3.3
  
  # Minimum required range between min and max for calibration to be accepted
  min_range: 0.005
  
  # Hysteresis band for state changes in the normalized signales (so between -1 and +1)
  hysteresis_band: 0.5
  
  # If flow drops to less than this fraction, assume flow has ended (or a new flow level has started).
  reset_fraction: 0.5
  # Maximum reset duration in milliseconds
  max_reset_duration: 120000

  # Liters per full rotation
  liters_per_rotation: 1.0
  # Amount of liters corresponding to the min/max calibration phase
  calibration_liters: 2.0

  # Number of calibration updates to perform for the fraction values after detecting a new phase, before considering the fraction calibrated. 
  # The total amount of water needed for this calibration is ~ calibration_liters + 2 + calibration_fraction_count*liters_per_rotation
  calibration_fraction_count: 3
  
  # Whether to wait for an API connection before processing readings. This can be useful for debugging to ensure you see all logs from the start of the process.
  wait_for_api_connection: false
  
  # Maximum number of phases (should be multiple of 6, and at least as high as the number of phases in your meter, e.g. 6 for a standard meter, 12 for a meter with two bright fields on the disk)
  max_phase_count: 12
  
esphome:
  name: "muino-water-meter"
  friendly_name: "Muino Water Meter"
  name_add_mac_suffix: true

  # This will allow for (future) project identification, configuration and updates.
  project:
    name: esphome.muino-water-meter
    version: "5.0.1"
    
  platformio_options:
    build_flags:
      - -D MIN_RANGE=${min_range}
      - -D HYSTERESIS_BAND=${hysteresis_band}
      - -D RESET_FRACTION=${reset_fraction}
      - -D MAX_RESET_DURATION=${max_reset_duration}
      - -D LITERS_PER_ROTATION=${liters_per_rotation}
      - -D CALIBRATION_LITERS=${calibration_liters}
      - -D CALIBRATION_FRACTION_COUNT=${calibration_fraction_count}
      - -D WAIT_FOR_API_CONNECTION=${1 if wait_for_api_connection else 0}
      - -D MAX_PHASE_COUNT=${max_phase_count}
    
  includes:
    - muino-water-meter-esp32.h

  on_boot:
    priority: -10
    then:
      # Initialize the global variable for lifetime consumption and sensor values to defaults.
      - lambda: |-
          id(consumption_lifetime).publish_state(id(global_consumption_lifetime));
          id(consumption_lifetime_number).publish_state(id(global_consumption_lifetime));
          id(consumption_since_restart).publish_state(0.0);
          id(flow_rate_current).publish_state(0.0);
          id(flow_rate_previous).publish_state(0.0);
          id(flow_rate_now).publish_state(0.0);
          id(consumption_current).publish_state(0.0);
          id(consumption_previous).publish_state(0.0);
          id(calibration_state).update();
          id(debug_json).publish_state("");

# This should point to the public location of this yaml file.
dashboard_import:
  package_import_url: github://martijnvwezel/watermeter-esphome/muino-water-meter-esp32.yaml@main

esp32:
  board: seeed_xiao_esp32c3
  framework:
    type: esp-idf

# Make sure logging is correct for solving platform IO bugs
logger:
  hardware_uart: USB_SERIAL_JTAG
  level: INFO

# Enable Home Assistant API
api:

# OTA is required for Over-the-Air updating
ota:
  platform: esphome

# Set up a wifi access point using the device name above
wifi:
  ap:

# In combination with the `ap` this allows the user to provision wifi credentials to the device.
captive_portal:

# Define entities
switch:
  - platform: template
    optimistic: true
    id: debug_mode
    name: "Debug Mode"
    icon: "mdi:bug"
    entity_category: "diagnostic"
    disabled_by_default: true

button:
  - platform: template
    id: reset_calibration
    name: "Reset Calibration"
    icon: "mdi:restart"
    entity_category: "config"
    disabled_by_default: true
    on_press:
      - lambda: reset_calibration_internal();

  - platform: restart
    name: "Restart"
    entity_category: "config"
    disabled_by_default: true

text_sensor:
  - platform: template
    id: debug_json
    name: "Debug JSON"
    icon: "mdi:code-json"
    entity_category: "diagnostic"
    update_interval: never
    disabled_by_default: true
  
  - platform: template
    id: calibration_state
    name: "Calibration Status"
    icon: "mdi:tune"
    entity_category: "diagnostic"
    update_interval: never
    lambda: return std::string(get_current_calibration_state_name());

output:
  - platform: gpio
    pin: 7
    id: led
  - platform: gpio
    pin: 6
    id: sensor_power

sensor:
  - &adc_common
    platform: adc
    # don't do automatic updates: it interfers with the timing of the readings in the interval and script sections.
    update_interval: never
    # samples uses an integer internally to do the avereging and therefore looses precision, 
    # so we do the averaging with a sliding_window_moving_average filter instead.
    entity_category: "diagnostic"
    internal: true
    pin:
      number: 2
      allow_other_uses: true
      ignore_strapping_warning: true
    id: light_sensor_a_dark
    name: "Light Sensor A Dark"
    filters:
      - clamp:
          min_value: ${lower_bound}
          max_value: ${upper_bound}
          ignore_out_of_range: true
      - sliding_window_moving_average:
          window_size: ${window_size * samples_per_reading}
          send_every: ${samples_per_reading}
          send_first_at: ${samples_per_reading}

  - <<: *adc_common
    pin:
      number: 3
      allow_other_uses: true
    id: light_sensor_b_dark
    name: "Light Sensor B Dark"
  - <<: *adc_common
    pin:
      number: 4
      allow_other_uses: true
    id: light_sensor_c_dark
    name: "Light Sensor C Dark"
  - <<: *adc_common
    pin:
      number: 2
      allow_other_uses: true
      ignore_strapping_warning: true
    id: light_sensor_a_light
    name: "Light Sensor A Light"
  - <<: *adc_common
    pin:
      number: 3
      allow_other_uses: true
    id: light_sensor_b_light
    name: "Light Sensor B Light"
  - <<: *adc_common
    pin:
      number: 4
      allow_other_uses: true
    id: light_sensor_c_light
    name: "Light Sensor C Light"
   
  - &diff_common
    platform: template
    name: "light_sensor_a_diff"
    id: light_sensor_a_diff
    lambda: return id(light_sensor_a_light).state - id(light_sensor_a_dark).state;
    update_interval: never
    internal: true
    filters:
      # skip inital readings to allow sensors to stabilize.
      - skip_initial: ${initialization_readings}
          
  - <<: *diff_common
    id: light_sensor_b_diff
    name: "light_sensor_b_diff"
    lambda: return id(light_sensor_b_light).state - id(light_sensor_b_dark).state;
     
  - <<: *diff_common
    id: light_sensor_c_diff
    name: "light_sensor_c_diff"
    lambda: return id(light_sensor_c_light).state - id(light_sensor_c_dark).state;

  # Consumption sensors
  - &consumption_common
    platform: template
    name: "Lifetime Consumption"
    id: consumption_lifetime
    device_class: "water"
    unit_of_measurement: "L"
    accuracy_decimals: 2
    update_interval: never
    state_class: total_increasing
    
  - <<: *consumption_common
    id: consumption_since_restart
    name: "Consumption since restart"

  - <<: *consumption_common
    id: consumption_current
    name: "Current Consumption"

  - <<: *consumption_common
    id: consumption_previous
    name: "Previous Consumption"

  # Flow rate sensors
  - &flow_rate_common
    platform: template
    name: "Instant Flow Rate"
    id: flow_rate_now
    device_class: "volume_flow_rate"
    unit_of_measurement: "L/min"
    accuracy_decimals: 2
    update_interval: never
    state_class: measurement

  - <<: *flow_rate_common
    id: flow_rate_current
    name: "Current Flow Rate"

  - <<: *flow_rate_common
    id: flow_rate_previous
    name: "Previous Flow Rate"

number:
  - platform: template
    id: consumption_lifetime_number
    name: "Lifetime Consumption"
    entity_category: "config"
    device_class: "water"
    unit_of_measurement: "L"
    update_interval: never
    min_value: 0
    max_value: 1000000000
    step: 1e-9
    set_action:
      - lambda: |- 
          id(global_consumption_lifetime) = x;
          id(consumption_lifetime).publish_state(x);

  - platform: template
    id: nr_phases
    name: "Number of Phases"
    min_value: 6
    max_value: ${max_phase_count}
    initial_value: 6
    step: 6
    mode: slider
    entity_category: "config"
    update_interval: never
    restore_value: true
    optimistic: true
    disabled_by_default: true
    set_action:
      - lambda: nr_phases_changed();

  - &num_common
    platform: template
    id: min_a
    name: "Min A"
    min_value: 0
    max_value: ${upper_bound}
    initial_value: 0
    entity_category: "config"
    device_class: "voltage"
    unit_of_measurement: "V"
    step: 1e-9
    update_interval: never
    restore_value: true
    optimistic: true
    disabled_by_default: true

  - <<: *num_common
    id: min_b
    name: "Min B"

  - <<: *num_common
    id: min_c
    name: "Min C"

  - <<: *num_common
    id: max_a
    name: "Max A"

  - <<: *num_common
    id: max_b
    name: "Max B"

  - <<: *num_common
    id: max_c
    name: "Max C"

  - &pattern_common
    platform: template
    id: pattern_0
    name: "Pattern for Phase 0"
    min_value: -1
    max_value: 8
    initial_value: -1
    entity_category: "config"
    step: 1
    mode: box
    update_interval: never
    disabled_by_default: true
    optimistic: true
    restore_value: true

  - <<: *pattern_common
    id: pattern_1
    name: "Pattern for Phase 1"
  - <<: *pattern_common
    id: pattern_2
    name: "Pattern for Phase 2"
  - <<: *pattern_common
    id: pattern_3
    name: "Pattern for Phase 3"
  - <<: *pattern_common
    id: pattern_4
    name: "Pattern for Phase 4"
  - <<: *pattern_common
    id: pattern_5
    name: "Pattern for Phase 5"
  - <<: *pattern_common
    id: pattern_6
    name: "Pattern for Phase 6"
  - <<: *pattern_common
    id: pattern_7
    name: "Pattern for Phase 7"
  - <<: *pattern_common
    id: pattern_8
    name: "Pattern for Phase 8"
  - <<: *pattern_common
    id: pattern_9
    name: "Pattern for Phase 9"
  - <<: *pattern_common
    id: pattern_10
    name: "Pattern for Phase 10"
  - <<: *pattern_common
    id: pattern_11
    name: "Pattern for Phase 11"

  - &fraction_common
    platform: template
    id: fraction_0
    name: "Liters for Phase 0"
    min_value: -0.001
    max_value: ${liters_per_rotation}
    initial_value: -0.001
    entity_category: "config"
    device_class: "water"
    unit_of_measurement: "L"
    step: 1e-9
    update_interval: never
    disabled_by_default: true
    optimistic: true
    restore_value: true

  - <<: *fraction_common
    id: fraction_1
    name: "Liters for Phase 1"
  - <<: *fraction_common
    id: fraction_2
    name: "Liters for Phase 2"
  - <<: *fraction_common
    id: fraction_3
    name: "Liters for Phase 3"
  - <<: *fraction_common
    id: fraction_4
    name: "Liters for Phase 4"
  - <<: *fraction_common
    id: fraction_5
    name: "Liters for Phase 5"
  - <<: *fraction_common
    id: fraction_6
    name: "Liters for Phase 6"
  - <<: *fraction_common
    id: fraction_7
    name: "Liters for Phase 7"
  - <<: *fraction_common
    id: fraction_8
    name: "Liters for Phase 8"
  - <<: *fraction_common
    id: fraction_9
    name: "Liters for Phase 9"
  - <<: *fraction_common
    id: fraction_10
    name: "Liters for Phase 10"
  - <<: *fraction_common
    id: fraction_11
    name: "Liters for Phase 11"
    
globals:
  # sensors use float values, but we want to be able to set the lifetime consumption with 
  # higher precision, so we use a double for the global variable and publish it to the sensor 
  # when it changes.
  - id: global_consumption_lifetime
    type: double
    restore_value: true
  
# Trgger readings at a fixed interval, and execute the update_readings script
interval:
  - interval: ${sample_interval}
    startup_delay: ${sample_interval}
    then:
      - script.execute: update_readings

# Reads the ADC states, both dark and bright and processes the readings to calculate flow and consumption. 
# The timing of the readings is important, so we do this in a script.
script:
  - id: update_readings
    then:
      # Switch on the sensor power and wait a bit for the sensors to stabilize before taking readings.
      - output.turn_on: sensor_power
      - delay: 20ms
      # Take multiple readings in the dark that are averaged by the moving window.
      - repeat:
          count: ${samples_per_reading}
          then:
            - component.update: light_sensor_a_dark
            - component.update: light_sensor_b_dark
            - component.update: light_sensor_c_dark
      # Turn on the led and wait a bit for the sensors to stabilize before taking readings.
      - output.turn_on: led
      - delay: 20ms
      # Take multiple readings in the light that are averaged by the moving window.
      - repeat:
          count: ${samples_per_reading}
          then:
            - component.update: light_sensor_a_light
            - component.update: light_sensor_a_diff
            - component.update: light_sensor_b_light
            - component.update: light_sensor_b_diff
            - component.update: light_sensor_c_light
            - component.update: light_sensor_c_diff
      # Turn off the led and sensor power.
      - output.turn_off: led
      - output.turn_off: sensor_power
      # Process the readings to calculate flow and consumption, and update the sensors accordingly.
      - lambda: process_readings();
      
