title: Muino Water Meter Reader
description: Firmware installer and setup guide for the Muino Smart Water Meter Reader
url: https://watermeter.muino.nl
baseurl: ""
defaults:
  - scope:
      path: ""
    values:
      layout: default
